20260183

Don Anton Niluksha Dilshan Edirisinghe

Goal: Use a pretrained model (e.g., distilbert-base-uncased-finetuned-sst-2-english)
Requirements:

• Use Hugging Face pipeline or Trainer API
• Run inference on at least 20 custom sentences
• Log the following in MLflow:– Model name– Number of samples– Accuracy– Predictions as an artifact (CSV)

Task 1 run 1

In [2]:
import os

os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

from transformers import pipeline
import mlflow
import pandas as pd

# Pretrained model
model_1 = "distilbert-base-uncased-finetuned-sst-2-english"

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model=model_1,
    device=-1
)

print("Model loaded successfully!")

Model loaded successfully!

In [3]:
sentences_run1 = [
    "The new laptop works incredibly well.",
    "I was impressed by how quickly the package arrived.",
    "The staff were friendly and helpful.",
    "The hotel provided excellent service throughout my stay.",
    "I am pleased with the quality of this product.",
    "The presentation was clear, informative, and engaging.",
    "The app makes managing my tasks much easier.",
    "The meal was delicious and beautifully prepared.",
    "The training session was useful and well organized.",
    "I had a pleasant experience with the company.",

    "The laptop stopped working after only a few days.",
    "The package arrived late and damaged.",
    "The staff were rude and unhelpful.",
    "The hotel service was disappointing.",
    "The product feels cheap and poorly made.",
    "The presentation was confusing and difficult to follow.",
    "The app is slow and frustrating to use.",
    "The meal was cold and tasteless.",
    "The training session was poorly organized and unhelpful.",
    "I had a terrible experience with the company."
]

true_labels_run1 = [
    "POSITIVE", "POSITIVE", "POSITIVE", "POSITIVE", "POSITIVE",
    "POSITIVE", "POSITIVE", "POSITIVE", "POSITIVE", "POSITIVE",

    "NEGATIVE", "NEGATIVE", "NEGATIVE", "NEGATIVE", "NEGATIVE",
    "NEGATIVE", "NEGATIVE", "NEGATIVE", "NEGATIVE", "NEGATIVE"
]

print("Run 1 samples:", len(sentences_run1))

Run 1 samples: 20

In [4]:
predicted_labels_run1 = []
confidence_scores_run1 = []

print("Starting Run 1 inference...\n")

for i, sentence in enumerate(sentences_run1):

    result = sentiment_pipeline(sentence)[0]

    predicted_labels_run1.append(result["label"])
    confidence_scores_run1.append(result["score"])

    print(f"{i + 1}/20 completed")

print("\nRun 1 inference completed!")

Starting Run 1 inference...

1/20 completed
2/20 completed
3/20 completed
4/20 completed
5/20 completed
6/20 completed
7/20 completed
8/20 completed
9/20 completed
10/20 completed
11/20 completed
12/20 completed
13/20 completed
14/20 completed
15/20 completed
16/20 completed
17/20 completed
18/20 completed
19/20 completed
20/20 completed

Run 1 inference completed!

In [5]:
correct_run1 = sum(
    actual == predicted
    for actual, predicted in zip(
        true_labels_run1,
        predicted_labels_run1
    )
)

accuracy_run1 = correct_run1 / len(sentences_run1)

print("Run 1 Accuracy:", accuracy_run1)

results_run1 = pd.DataFrame({
    "sentence": sentences_run1,
    "true_label": true_labels_run1,
    "predicted_label": predicted_labels_run1,
    "confidence": confidence_scores_run1
})

csv_run1 = "sentiment_predictions_run1.csv"

results_run1.to_csv(csv_run1, index=False)

display(results_run1)

Run 1 Accuracy: 1.0

,sentence,true_label,predicted_label,confidence
0,The new laptop works incredibly well.,POSITIVE,POSITIVE,0.999841
1,I was impressed by how quickly the package arr...,POSITIVE,POSITIVE,0.999718
2,The staff were friendly and helpful.,POSITIVE,POSITIVE,0.999849
3,The hotel provided excellent service throughou...,POSITIVE,POSITIVE,0.999788
4,I am pleased with the quality of this product.,POSITIVE,POSITIVE,0.999868
5,"The presentation was clear, informative, and e...",POSITIVE,POSITIVE,0.999873
6,The app makes managing my tasks much easier.,POSITIVE,POSITIVE,0.977244
7,The meal was delicious and beautifully prepared.,POSITIVE,POSITIVE,0.999886
8,The training session was useful and well organ...,POSITIVE,POSITIVE,0.999851
9,I had a pleasant experience with the company.,POSITIVE,POSITIVE,0.999875
10,The laptop stopped working after only a few days.,NEGATIVE,NEGATIVE,0.999086
11,The package arrived late and damaged.,NEGATIVE,NEGATIVE,0.999588
12,The staff were rude and unhelpful.,NEGATIVE,NEGATIVE,0.999047
13,The hotel service was disappointing.,NEGATIVE,NEGATIVE,0.999736
14,The product feels cheap and poorly made.,NEGATIVE,NEGATIVE,0.999823
15,The presentation was confusing and difficult t...,NEGATIVE,NEGATIVE,0.999734
16,The app is slow and frustrating to use.,NEGATIVE,NEGATIVE,0.999696
17,The meal was cold and tasteless.,NEGATIVE,NEGATIVE,0.998709
18,The training session was poorly organized and ...,NEGATIVE,NEGATIVE,0.999803
19,I had a terrible experience with the company.,NEGATIVE,NEGATIVE,0.999222

In [6]:
mlflow.set_experiment("HuggingFace_Sentiment_Analysis")

with mlflow.start_run(run_name="Sentiment_model_Run_1"):

    mlflow.log_param("model_name", model_1)
    mlflow.log_param("number_of_samples", len(sentences_run1))

    mlflow.log_metric("accuracy", accuracy_run1)

    mlflow.log_artifact(csv_run1)

    print("MLflow for sentiment analysis Run 1 completed!")

2026/08/15 20:43:21 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/08/15 20:43:21 INFO mlflow.store.db.utils: Updating database tables
2026/08/15 20:43:23 INFO mlflow.tracking.fluent: Experiment with name 'HuggingFace_Sentiment_Analysis' does not exist. Creating a new experiment.
2026/08/15 20:43:27 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

2026/08/15 20:43:27 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git branch is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

2026/08/15 20:43:27 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git repository URL is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

MLflow for sentiment analysis Run 1 completed!

Task 1 run 2

In [7]:
sentences_run2 = [
    "The customer service representative solved my issue quickly.",
    "The camera takes sharp and beautiful photos.",
    "I really enjoyed the online course.",
    "The delivery arrived earlier than expected.",
    "The new design looks modern and attractive.",
    "The staff made us feel very welcome.",
    "This restaurant has some of the best food in town.",
    "The instructions were simple and easy to understand.",
    "The product exceeded everything I expected.",
    "I am very happy with the final result.",

    "The customer service team ignored my complaint.",
    "The camera produces blurry and disappointing photos.",
    "I found the online course boring and unhelpful.",
    "The delivery arrived several days late.",
    "The new design looks outdated and unattractive.",
    "The staff were unfriendly and impatient.",
    "The food at this restaurant was unpleasant.",
    "The instructions were confusing and incomplete.",
    "The product failed to meet my expectations.",
    "I am very disappointed with the final result."
]

true_labels_run2 = [
    "POSITIVE", "POSITIVE", "POSITIVE", "POSITIVE", "POSITIVE",
    "POSITIVE", "POSITIVE", "POSITIVE", "POSITIVE", "POSITIVE",

    "NEGATIVE", "NEGATIVE", "NEGATIVE", "NEGATIVE", "NEGATIVE",
    "NEGATIVE", "NEGATIVE", "NEGATIVE", "NEGATIVE", "NEGATIVE"
]

print("Run 2 samples:", len(sentences_run2))

Run 2 samples: 20

In [8]:
predicted_labels_run2 = []
confidence_scores_run2 = []

print("Starting Run 2 inference...\n")

for i, sentence in enumerate(sentences_run2):

    result = sentiment_pipeline(sentence)[0]

    predicted_labels_run2.append(result["label"])
    confidence_scores_run2.append(result["score"])

    print(f"{i + 1}/20 completed")

print("\nRun 2 inference completed!")

Starting Run 2 inference...

1/20 completed
2/20 completed
3/20 completed
4/20 completed
5/20 completed
6/20 completed
7/20 completed
8/20 completed
9/20 completed
10/20 completed
11/20 completed
12/20 completed
13/20 completed
14/20 completed
15/20 completed
16/20 completed
17/20 completed
18/20 completed
19/20 completed
20/20 completed

Run 2 inference completed!

In [9]:
correct_run2 = sum(
    actual == predicted
    for actual, predicted in zip(
        true_labels_run2,
        predicted_labels_run2
    )
)

accuracy_run2 = correct_run2 / len(sentences_run2)

print("Run 2 Accuracy:", accuracy_run2)

results_run2 = pd.DataFrame({
    "sentence": sentences_run2,
    "true_label": true_labels_run2,
    "predicted_label": predicted_labels_run2,
    "confidence": confidence_scores_run2
})

csv_run2 = "sentiment_predictions_run2.csv"

results_run2.to_csv(csv_run2, index=False)

display(results_run2)

Run 2 Accuracy: 0.9

,sentence,true_label,predicted_label,confidence
0,The customer service representative solved my ...,POSITIVE,NEGATIVE,0.515307
1,The camera takes sharp and beautiful photos.,POSITIVE,POSITIVE,0.999833
2,I really enjoyed the online course.,POSITIVE,POSITIVE,0.999850
3,The delivery arrived earlier than expected.,POSITIVE,NEGATIVE,0.982480
4,The new design looks modern and attractive.,POSITIVE,POSITIVE,0.999854
5,The staff made us feel very welcome.,POSITIVE,POSITIVE,0.999861
6,This restaurant has some of the best food in t...,POSITIVE,POSITIVE,0.999842
7,The instructions were simple and easy to under...,POSITIVE,POSITIVE,0.998016
8,The product exceeded everything I expected.,POSITIVE,POSITIVE,0.996752
9,I am very happy with the final result.,POSITIVE,POSITIVE,0.999878
10,The customer service team ignored my complaint.,NEGATIVE,NEGATIVE,0.992319
11,The camera produces blurry and disappointing p...,NEGATIVE,NEGATIVE,0.999809
12,I found the online course boring and unhelpful.,NEGATIVE,NEGATIVE,0.999813
13,The delivery arrived several days late.,NEGATIVE,NEGATIVE,0.992732
14,The new design looks outdated and unattractive.,NEGATIVE,NEGATIVE,0.999794
15,The staff were unfriendly and impatient.,NEGATIVE,NEGATIVE,0.999422
16,The food at this restaurant was unpleasant.,NEGATIVE,NEGATIVE,0.999625
17,The instructions were confusing and incomplete.,NEGATIVE,NEGATIVE,0.999672
18,The product failed to meet my expectations.,NEGATIVE,NEGATIVE,0.999782
19,I am very disappointed with the final result.,NEGATIVE,NEGATIVE,0.999778

In [10]:
model_1 = "distilbert-base-uncased-finetuned-sst-2-english"

mlflow.set_experiment("HuggingFace_Sentiment_Analysis")

with mlflow.start_run(run_name="Sentiment_Run_2"):

    mlflow.log_param(
        "model_name",
        model_1
    )

    mlflow.log_param(
        "number_of_samples",
        len(sentences_run2)
    )

    mlflow.log_metric(
        "accuracy",
        accuracy_run2
    )

    mlflow.log_artifact(csv_run2)

    print("MLflow Sentiment Run 2 completed!")

MLflow Sentiment Run 2 completed!

Observation: The pretrained DistilBERT sentiment analysis model successfully classified the 20 custom sentences in each run as positive or negative. The model performed well on both datasets, with most sentences receiving high-confidence predictions. The results demonstrate that the pretrained model can effectively identify sentiment in different types of customer service, product, and experience-related sentences.

Task 2: Named Entity Recognition
Goal: Use a pretrained NER model (e.g., dslim/bert-base-NER)
Requirements:
• Run on at least 10 paragraphs
• Extract entities:
– Person
– Organization
– Location
• Log:
– Model name
– Total entities extracted
– Distribution of entity types
– Output a file as artifact

Task 1 run 1

In [11]:
import os

os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

from transformers import pipeline
import mlflow
import pandas as pd
from collections import Counter

# Pretrained NER model
ner_model_name = "dslim/bert-base-NER"

ner_pipeline = pipeline(
    "ner",
    model=ner_model_name,
    aggregation_strategy="simple",
    device=-1
)

print("NER model loaded successfully!")

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  |
bert.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

NER model loaded successfully!

In [12]:
paragraphs_run1 = [
    """Mary Kom trained for many years in Manipur before becoming an
    internationally recognized boxer. She represented India in several
    competitions and received support from the Sports Authority of India
    in New Delhi.""",

    """Tim Berners-Lee invented the World Wide Web while working at CERN
    in Geneva. His work changed how people access information on the
    internet, and CERN continues to support scientific research in
    Switzerland.""",

    """Indra Nooyi served as the chief executive officer of PepsiCo.
    During her career, she worked with teams in New York and other parts
    of the United States to expand the company's global business.""",

    """The World Health Organization organized a conference in Geneva
    where Tedros Adhanom Ghebreyesus spoke about international health
    cooperation. Representatives from Japan, Canada, and Australia
    attended the event.""",

    """Sachin Tendulkar played international cricket for India for many
    years. He represented Mumbai in domestic competitions and played at
    famous stadiums across India, including venues in Mumbai and Delhi.""",

    """Amazon Web Services announced a new cloud computing program in
    Austin. Andy Jassy discussed the company's plans to help businesses
    across Texas adopt cloud technologies and improve their digital
    infrastructure.""",

    """Malala Yousafzai visited New York to attend an education event
    organized by the Malala Fund. She spoke with students and educators
    about improving access to education for children around the world.""",

    """Toyota introduced a new electric vehicle at an event in Tokyo.
    Akio Toyoda discussed the company's plans to invest in sustainable
    transportation and expand production facilities across Japan.""",

    """Leonardo da Vinci spent part of his life in Florence, where he
    created several important works of art. His work was later studied
    by researchers and historians at institutions throughout Italy.""",

    """The International Monetary Fund held discussions in Washington,
    D.C., with representatives from Germany, France, and Brazil.
    Kristalina Georgieva addressed economic challenges and encouraged
    cooperation between member countries."""
]

print("Run 1 paragraphs:", len(paragraphs_run1))

Run 1 paragraphs: 10

In [13]:
entities_run1 = []

print("Starting Run 1 NER...\n")

for i, paragraph in enumerate(paragraphs_run1):

    results = ner_pipeline(paragraph)

    for entity in results:

        entity_type = entity["entity_group"]

        # Keep only required entity types
        if entity_type in ["PER", "ORG", "LOC"]:

            entities_run1.append({
                "paragraph": i + 1,
                "entity": entity["word"],
                "entity_type": entity_type,
                "confidence": entity["score"]
            })

    print(f"{i + 1}/10 paragraphs completed")

print("\nRun 1 NER completed!")
print("Total entities:", len(entities_run1))

Starting Run 1 NER...

1/10 paragraphs completed
2/10 paragraphs completed
3/10 paragraphs completed
4/10 paragraphs completed
5/10 paragraphs completed
6/10 paragraphs completed
7/10 paragraphs completed
8/10 paragraphs completed
9/10 paragraphs completed
10/10 paragraphs completed

Run 1 NER completed!
Total entities: 53

In [14]:
from collections import Counter

# Count entity types
entity_counts_run1 = Counter(
    entity["entity_type"]
    for entity in entities_run1
)

person_count_run1 = entity_counts_run1.get("PER", 0)
organization_count_run1 = entity_counts_run1.get("ORG", 0)
location_count_run1 = entity_counts_run1.get("LOC", 0)

print("Run 1 entity distribution:")
print("Person:", person_count_run1)
print("Organization:", organization_count_run1)
print("Location:", location_count_run1)
print("Total:", len(entities_run1))

# Create DataFrame
entities_df_run1 = pd.DataFrame(entities_run1)

# Save CSV
ner_csv_run1 = "ner_entities_run1.csv"

entities_df_run1.to_csv(
    ner_csv_run1,
    index=False
)

display(entities_df_run1)

Run 1 entity distribution:
Person: 17
Organization: 9
Location: 27
Total: 53

    paragraph                       entity entity_type  confidence
0           1                     Mary Kom         PER    0.986575
1           1                      Manipur         LOC    0.998017
2           1                        India         LOC    0.999759
3           1    Sports Authority of India         ORG    0.999185
4           1                    New Delhi         LOC    0.999451
5           2                  Tim Berners         PER    0.999472
6           2                          Lee         PER    0.817263
7           2                         CERN         ORG    0.994994
8           2                       Geneva         LOC    0.999346
9           2                         CERN         ORG    0.993881
10          2                  Switzerland         LOC    0.999759
11          3                           In         PER    0.999300
12          3                   ##dra Nooy         PER    0.993885
13          3                      PepsiCo         ORG    0.994807
14          3                     New York         LOC    0.999177
15          3                United States         LOC    0.999451
16          4    World Health Organization         ORG    0.998975
17          4                       Geneva         LOC    0.999525
18          4                          Ted         PER    0.999440
19          4    ##ros Adhanom Ghebreyesus         PER    0.946535
20          4                        Japan         LOC    0.999823
21          4                       Canada         LOC    0.999808
22          4                    Australia         LOC    0.999813
23          5                           Sa         PER    0.999646
24          5             ##chin Tendulkar         PER    0.931874
25          5                        India         LOC    0.999817
26          5                       Mumbai         LOC    0.975515
27          5                        India         LOC    0.999322
28          5                       Mumbai         LOC    0.999504
29          5                        Delhi         LOC    0.999388
30          6          Amazon Web Services         ORG    0.999309
31          6                       Austin         LOC    0.999260
32          6                   Andy Jassy         PER    0.999071
33          6                        Texas         LOC    0.999610
34          7             Malala Yousafzai         PER    0.948713
35          7                     New York         LOC    0.999443
36          7                  Malala Fund         ORG    0.998593
37          8                       Toyota         ORG    0.998893
38          8                        Tokyo         LOC    0.999377
39          8                            A         PER    0.999627
40          8                 ##kio Toyoda         PER    0.927338
41          8                        Japan         LOC    0.999697
42          9            Leonardo da Vinci         PER    0.995670
43          9                     Florence         LOC    0.999664
44          9                        Italy         LOC    0.999683
45         10  International Monetary Fund         ORG    0.999321
46         10            Washington, D. C.         LOC    0.988026
47         10                      Germany         LOC    0.999662
48         10                       France         LOC    0.999677
49         10                       Brazil         LOC    0.999723
50         10                         Kris         PER    0.999475
51         10                        ##tal         PER    0.992416
52         10                ##ina Georgie         PER    0.790627

In [15]:
mlflow.set_experiment("HuggingFace_NER")

with mlflow.start_run(run_name="NER_Run_1"):

    # Parameter
    mlflow.log_param(
        "model_name",
        ner_model_name
    )

    # Metrics
    mlflow.log_metric(
        "total_entities_extracted",
        len(entities_run1)
    )

    mlflow.log_metric(
        "person_entities",
        person_count_run1
    )

    mlflow.log_metric(
        "organization_entities",
        organization_count_run1
    )

    mlflow.log_metric(
        "location_entities",
        location_count_run1
    )

    # Artifact
    mlflow.log_artifact(ner_csv_run1)

    print("MLflow NER Run 1 completed!")

2026/08/15 20:54:37 INFO mlflow.tracking.fluent: Experiment with name 'HuggingFace_NER' does not exist. Creating a new experiment.

MLflow NER Run 1 completed!

Task 2 run 2

In [16]:
paragraphs_run2 = [
    """Marie Curie conducted important scientific research in Paris.
    She worked with Pierre Curie and became one of the most influential
    scientists associated with the University of Paris.""",

    """Satya Nadella spoke at a Microsoft event in London about the
    future of cloud computing. Microsoft announced several new services
    designed to support businesses across Europe.""",

    """Nelson Mandela visited London during his international campaign
    for human rights. He worked with organizations including the African
    National Congress to promote equality in South Africa.""",

    """The International Olympic Committee organized a meeting in
    Lausanne, Switzerland. Thomas Bach discussed preparations for future
    Olympic Games with representatives from several countries.""",

    """Walt Disney established the Disney Brothers Studio in California.
    The company later became The Walt Disney Company and expanded its
    entertainment business around the world.""",

    """Serena Williams competed in Melbourne during the Australian Open.
    She worked with her coaching team to prepare for the tournament and
    represented the United States throughout her tennis career.""",

    """The National Aeronautics and Space Administration launched a
    research mission from Florida. NASA engineers worked with scientists
    in Houston to monitor the spacecraft during its journey.""",

    """Ratan Tata led the Tata Group for many years and helped expand
    the organization internationally. The company has major operations
    in Mumbai and other cities across India.""",

    """Adele performed at a music festival in Sydney after completing
    several concerts across Australia. The event was attended by fans
    from Melbourne, Brisbane, and other Australian cities.""",

    """The United Nations Children's Fund opened a new education
    initiative in Nairobi. UNICEF representatives worked with local
    organizations in Kenya to support children and schools."""
]

print("Run 2 paragraphs:", len(paragraphs_run2))

Run 2 paragraphs: 10

In [17]:
entities_run2 = []

print("Starting Run 2 NER...\n")

for i, paragraph in enumerate(paragraphs_run2):

    results = ner_pipeline(paragraph)

    for entity in results:

        entity_type = entity["entity_group"]

        if entity_type in ["PER", "ORG", "LOC"]:

            entities_run2.append({
                "paragraph": i + 1,
                "entity": entity["word"],
                "entity_type": entity_type,
                "confidence": entity["score"]
            })

    print(f"{i + 1}/10 paragraphs completed")

print("\nRun 2 NER completed!")
print("Total entities:", len(entities_run2))

Starting Run 2 NER...

1/10 paragraphs completed
2/10 paragraphs completed
3/10 paragraphs completed
4/10 paragraphs completed
5/10 paragraphs completed
6/10 paragraphs completed
7/10 paragraphs completed
8/10 paragraphs completed
9/10 paragraphs completed
10/10 paragraphs completed

Run 2 NER completed!
Total entities: 42

In [18]:
entity_counts_run2 = Counter(
    entity["entity_type"]
    for entity in entities_run2
)

person_count_run2 = entity_counts_run2.get("PER", 0)
organization_count_run2 = entity_counts_run2.get("ORG", 0)
location_count_run2 = entity_counts_run2.get("LOC", 0)

print("Run 2 entity distribution:")
print("Person:", person_count_run2)
print("Organization:", organization_count_run2)
print("Location:", location_count_run2)
print("Total:", len(entities_run2))

# Create DataFrame
entities_df_run2 = pd.DataFrame(entities_run2)

# Save CSV
ner_csv_run2 = "ner_entities_run2.csv"

entities_df_run2.to_csv(
    ner_csv_run2,
    index=False
)

display(entities_df_run2)

Run 2 entity distribution:
Person: 10
Organization: 12
Location: 20
Total: 42

,paragraph,entity,entity_type,confidence
0,1,Marie Curie,PER,0.973837
1,1,Paris,LOC,0.999610
2,1,Pierre Curie,PER,0.974661
3,1,University of Paris,ORG,0.996351
4,2,Sa,PER,0.999742
5,2,##tya Nadella,PER,0.834339
6,2,Microsoft,ORG,0.997361
7,2,London,LOC,0.999596
8,2,Microsoft,ORG,0.998635
9,2,Europe,LOC,0.999711
10,3,Nelson Mandela,PER,0.999236
11,3,London,LOC,0.999723
12,3,African National Congress,ORG,0.999429
13,3,South Africa,LOC,0.999163
14,4,International,ORG,0.903278
15,4,Lausanne,LOC,0.998935
16,4,Switzerland,LOC,0.999704
17,4,Thomas Bach,PER,0.999729
18,5,Walt Disney,PER,0.990762
19,5,Disney Brothers Studio,ORG,0.996181
20,5,California,LOC,0.999651
21,5,The Walt Disney Company,ORG,0.997981
22,6,Serena Williams,PER,0.999390
23,6,Melbourne,LOC,0.999466
24,6,United States,LOC,0.999526
25,7,National Aeronautics and Space Administration,ORG,0.999208
26,7,Florida,LOC,0.999635
27,7,NASA,ORG,0.998940
28,7,Houston,LOC,0.999173
29,8,Ratan Tata,PER,0.995227
30,8,Tata Group,ORG,0.998875
31,8,Mumbai,LOC,0.999428
32,8,India,LOC,0.999137
33,9,Adele,PER,0.975977
34,9,Sydney,LOC,0.999680
35,9,Australia,LOC,0.999761
36,9,Melbourne,LOC,0.999484
37,9,Brisbane,LOC,0.999285
38,10,United Nations Children ' s Fund,ORG,0.999339
39,10,Nairobi,LOC,0.999678
40,10,UNICEF,ORG,0.998967
41,10,Kenya,LOC,0.999801

In [19]:
mlflow.set_experiment("HuggingFace_NER")

with mlflow.start_run(run_name="NER_Run_2"):

    # Parameter
    mlflow.log_param(
        "model_name",
        ner_model_name
    )

    # Metrics
    mlflow.log_metric(
        "total_entities_extracted",
        len(entities_run2)
    )

    mlflow.log_metric(
        "person_entities",
        person_count_run2
    )

    mlflow.log_metric(
        "organization_entities",
        organization_count_run2
    )

    mlflow.log_metric(
        "location_entities",
        location_count_run2
    )

    # Artifact
    mlflow.log_artifact(ner_csv_run2)

    print("MLflow NER Run 2 completed!")

MLflow NER Run 2 completed!

Observation: The pretrained BERT NER model identified a variety of named entities from the provided paragraphs, including people, organizations, and locations. The extracted entities differed between the two runs because the paragraphs contained different names and places. Overall, the model was able to recognize the main entities associated with the given contexts.

Task 3: Text Generation Goal: Use a generative model (e.g., gpt2) Requirements: • Provide 5 prompts • Generate text using different parameters: – temperature – max_length • Log: – Parameters used – Generated outputs – Observations (as text artifact)

Task 3 run 1

In [20]:
import os

os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

from transformers import pipeline
import mlflow
import pandas as pd

# Pretrained generative model
generation_model_name = "gpt2"

generator = pipeline(
    "text-generation",
    model=generation_model_name,
    device=-1
)

print("GPT-2 model loaded successfully!")

GPT-2 model loaded successfully!

In [21]:
prompts_run1 = [
    "A healthy lifestyle begins with",
    "The best way to solve a difficult problem is",
    "Reading books can help people",
    "A successful team should always",
    "In the coming years, education will"
]

settings_run1 = [
    {"temperature": 0.5, "max_length": 50},
    {"temperature": 0.6, "max_length": 60},
    {"temperature": 0.5, "max_length": 55},
    {"temperature": 0.7, "max_length": 65},
    {"temperature": 0.6, "max_length": 60}
]

print("Run 1 prompts:", len(prompts_run1))

Run 1 prompts: 5

In [22]:
generated_results_run1 = []

print("Starting Run 1 text generation...\n")

for i, prompt in enumerate(prompts_run1):

    settings = settings_run1[i]

    result = generator(
        prompt,
        max_length=settings["max_length"],
        temperature=settings["temperature"],
        do_sample=True,
        num_return_sequences=1
    )

    generated_text = result[0]["generated_text"]

    generated_results_run1.append({
        "prompt": prompt,
        "temperature": settings["temperature"],
        "max_length": settings["max_length"],
        "generated_text": generated_text
    })

    print(f"{i + 1}/5 completed")
    print("Generated:", generated_text)
    print("-" * 70)

print("\nRun 1 generation completed!")

[transformers] Passing `generation_config` together with generation-related arguments=({'num_return_sequences', 'temperature', 'max_length', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

Starting Run 1 text generation...

[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=60) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1/5 completed
Generated: A healthy lifestyle begins with a healthy diet.

The following are some of the most common dietary supplements that you should take:

Dietary supplements:

Dietary supplements are the most common dietary supplements that you should take. The following are some of the most common dietary supplements that you should take:

Dietary supplements are the most common dietary supplements that you should take. The following are some of the most common dietary supplements that you should take:

Dietary supplements are the most common dietary supplements that you should take. The following are some of the most common dietary supplements that you should take:

Dietary supplements are the most common dietary supplements that you should take. The following are some of the most common dietary supplements that you should take:

Dietary supplements are the most common dietary supplements that you should take. The following are some of the most common dietary supplements that you should take:

Dietary supplements are the most common dietary supplements that you should take. The following are some of the most common dietary supplements that you should take:

Dietary supplements are the most common dietary supplements that you should take. The following are some of the most common dietary supplements that you should take:

Diet
----------------------------------------------------------------------

[transformers] Both `max_new_tokens` (=256) and `max_length`(=55) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

2/5 completed
Generated: The best way to solve a difficult problem is to solve it with the right tools, and to find solutions that are more consistent with your own.

Learn to write code

Writing code is a difficult skill, especially when it comes to writing complex software. However, there are many ways to learn how to write code.

Learning to write code is one of the best ways to get the most out of your time. You'll find that writing code is a great way to learn how to write code and to learn how to write code efficiently.

How to Write Code

Most people write code by hand and they don't need to do it all at once. The important thing is to pick the right tools and tools for writing code.

The most important tool is the IDE. If you want to write code in the IDE, you have to learn how to use the tools and code.

We all know about the Java IDE, but it's not the best tool. If you want to write code in a language that's not written in Java, then you have to learn how to use the tools and code.

The IDE is a great tool, but it's not the best way to write code. A lot of people write their code in a language that's not
----------------------------------------------------------------------

[transformers] Both `max_new_tokens` (=256) and `max_length`(=65) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

3/5 completed
Generated: Reading books can help people understand the world around them.

The book, which is published by the Oxford English Dictionary, is based on the works of the late British novelist and poet William Shakespeare.

The book is written by the author of "The Tempest," who was also the first person to write a story about war.

"The Tempest" is about the death of a man in 1801, and the aftermath of the war. The book was written by William Shakespeare, who was also a writer.

In the book, the war takes place in the year 1801, when the British army is made up of four companies.

The book is based on the works of Samuel Huntington, who was a writer.

"The Tempest" is a story about the death of a man in 1801, and the aftermath of the war.

The book is based on the works of Samuel Huntington, who was a writer.

The book is based on the works of Samuel Huntington, who was a writer.

The book is based on the works of Samuel Huntington, who was a writer.

The book is based on the works of Samuel Huntington, who was a writer.

The book is based on the works of Samuel Huntington,
----------------------------------------------------------------------

[transformers] Both `max_new_tokens` (=256) and `max_length`(=60) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

4/5 completed
Generated: A successful team should always be considered the best, and this was the case with the two men who were not only the best in competition, but also in the field of chess.

The second man that was not only the best but also the best in the field of chess was the young man who was a student of chess at the University of Amsterdam. This young man, Andreas Schliemann, played chess at the University of Amsterdam in the late 19th century, while he had a degree in art from the University of Amsterdam. During his time at the University of Amsterdam, Andreas Schliemann was a student of the same school, which was also the place where he had studied at the University of Amsterdam. He, along with his wife, went to the University of Amsterdam for a number of years, and he stayed there for more than a year.

A year later in 1904, after his 18th birthday, Andreas Schliemann went to a European Grand Prix. He had to beat, and defeat, the young German player, the man who had won the World Chess Championship in 1906. This young German player played chess for only one year, and he was very happy. He had been happy with his chess, but he was also very sad when he discovered that
----------------------------------------------------------------------
5/5 completed
Generated: In the coming years, education will increasingly be the focus of the public's attention.

And while the goal is to make the best of the digital world, there's a growing focus on how to bring it to life.

"The key is to have a very strong digital presence," said Thomas Beaudry, a professor at the University of Minnesota who has done extensive research into the use of digital technology in education. "It's not just about the classroom, it's about how you interact with the world, and that's what you're going to need to do to grow the digital presence in your education."

Beaudry and his colleagues at the University of Minnesota have found that students who learn in a traditional classroom are more likely to use the Internet when they're in a classroom than students who are in a public school.

"The key is to have a very strong digital presence," he said. "It's not just about the classroom, it's about how you interact with the world, and that's what you're going to need to do to grow the digital presence in your education."

The key is to have a very strong digital presence. It's not just about the classroom, it's about how you interact with the world, and that's what you
----------------------------------------------------------------------

Run 1 generation completed!

In [23]:
results_df_run1 = pd.DataFrame(generated_results_run1)

generation_csv_run1 = "generated_outputs_run1.csv"

results_df_run1.to_csv(
    generation_csv_run1,
    index=False
)

print("Run 1 output file created:", generation_csv_run1)

display(results_df_run1)

Run 1 output file created: generated_outputs_run1.csv

,prompt,temperature,max_length,generated_text
0,A healthy lifestyle begins with,0.5,50,A healthy lifestyle begins with a healthy diet...
1,The best way to solve a difficult problem is,0.6,60,The best way to solve a difficult problem is t...
2,Reading books can help people,0.5,55,Reading books can help people understand the w...
3,A successful team should always,0.7,65,A successful team should always be considered ...
4,"In the coming years, education will",0.6,60,"In the coming years, education will increasing..."

In [24]:
observations_run1 = """
Task 3 - Text Generation Run 1 Observations

In this run, GPT-2 generated responses for five different prompts
using relatively low temperature values.

The lower temperature settings made the generated text more
consistent and focused. The outputs generally followed the context
provided by each prompt with less variation.

The max_length values determined how long the generated responses
could become. Increasing max_length allowed the model to continue
the generated text for a longer sequence.

Overall, the first run demonstrated how conservative temperature
settings can produce more stable and predictable text generation.
"""

observations_path_run1 = "generation_observations_run1.txt"

with open(
    observations_path_run1,
    "w",
    encoding="utf-8"
) as file:
    file.write(observations_run1)

print("Observations file created:", observations_path_run1)

Observations file created: generation_observations_run1.txt

Task 3 run 2

In [25]:
prompts_run2 = [
    "Exploring a new country can teach us",
    "Creativity becomes stronger when",
    "A surprising discovery in science could",
    "Working with people from different cultures can",
    "The future of transportation might"
]

settings_run2 = [
    {"temperature": 1.0, "max_length": 70},
    {"temperature": 1.1, "max_length": 80},
    {"temperature": 1.0, "max_length": 75},
    {"temperature": 1.2, "max_length": 85},
    {"temperature": 1.1, "max_length": 75}
]

print("Run 2 prompts:", len(prompts_run2))

Run 2 prompts: 5

In [26]:
generated_results_run2 = []

print("Starting Run 2 text generation...\n")

for i, prompt in enumerate(prompts_run2):

    settings = settings_run2[i]

    result = generator(
        prompt,
        max_length=settings["max_length"],
        temperature=settings["temperature"],
        do_sample=True,
        num_return_sequences=1
    )

    generated_text = result[0]["generated_text"]

    generated_results_run2.append({
        "prompt": prompt,
        "temperature": settings["temperature"],
        "max_length": settings["max_length"],
        "generated_text": generated_text
    })

    print(f"{i + 1}/5 completed")
    print("Generated:", generated_text)
    print("-" * 70)

print("\nRun 2 generation completed!")

Starting Run 2 text generation...

[transformers] Both `max_new_tokens` (=256) and `max_length`(=70) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=256) and `max_length`(=80) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1/5 completed
Generated: Exploring a new country can teach us lessons, but it cannot stop us from making the best use of that knowledge.

I know for a fact that the countries of Eastern Europe have a very diverse ethnic makeup. Those ethnic minorities were at times called "Eastern Europeans". These people are as important to their national histories and cultures and to a great extent as the "Europeans" who made the western world what it is today.

Those people are often told about the European experience. We do the same with our homeland, and we are the people we are. We need to keep our culture alive.

We need to make the future of our land and national history our focus. Even our past should be filled from the perspective of those who created it. But in a world made in this way, we are losing and we must be conscious of our past.

I have no question it is my duty to remind myself. I have no doubt I am here to help you. But I do not want to discourage you from joining me on my journey to a greater, more prosperous world for all of us.

Until then, stay safe!

Das Kapital

Special Rapporteur on East Asian and Pacific Islander Affairs
----------------------------------------------------------------------

[transformers] Both `max_new_tokens` (=256) and `max_length`(=75) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

2/5 completed
Generated: Creativity becomes stronger when there is a higher-quality and clearer visualization of what's happening in this moment.

A lot of people are in a phase of having to do all sorts of visualizations of things over and over again and sometimes not getting the cues they need. However, I personally learned that I could achieve more about and insight by listening to how people view time and see themselves in the moment. They need the insight they get from looking at a big picture. This will only be realized by understanding the visual and process process and the dynamics within those processes and not just making an impression that someone else got it right.

One area where you can start to push back is that when the visual process has some subtle nuances you will then get used to making different interpretations more naturally, more easily, and you'll find it easier with experience.

But even if you have an open mind or a simple process or some combination of all these things – it's important to realize how you're able to actually improve the visual process. If you didn't grow up seeing the visual processes you understand differently and just go off and do one or one thing at a time, then you are likely going to get bored of the whole process process.

Even if that's the case if
----------------------------------------------------------------------

[transformers] Both `max_new_tokens` (=256) and `max_length`(=85) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

3/5 completed
Generated: A surprising discovery in science could have an important economic impact in understanding the human brain.

Scientists have long been concerned that our brains need money and power to run, but a new study by computer researchers highlights what could lie behind those concerns.

'Happiness' is just one of many factors as to why humans think differently. A new study suggests we are using more energy for our lives but can also use it to make better choices.

Researchers from the University of Leeds studied the brain development of 16 individuals, each having their own unique brain anatomy.

One person was left with a big difference - one hemisphere was bigger, while the other hemisphere was narrower - and then, as they became older, many of the participants 'were at risk that their brain health would suffer' from brain tumours

The researchers then measured the participants' brain tumour rates. They found that the smaller brains had more activity at the ends of their life but this was 'significantly more difficult to see' during the early stages of life, during which they were at risk of developing a new, healthier brain tumour

The researchers compared how active the larger brain's activity was between the ages of 10 and 13, so the researchers would need to see whether it was 'significantly more difficult
----------------------------------------------------------------------

[transformers] Both `max_new_tokens` (=256) and `max_length`(=75) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

4/5 completed
Generated: Working with people from different cultures can give you the resources you need to build that relationship. This is no longer done by a party or a couple, this has to work in tandem with the whole of the project."

In addition to helping the project in order. One reason is the increased emphasis on people from different cultures sharing their perspectives and perspectives on the project. If the social media company doesn't follow through their target audiences' expectations on providing culturally sensitive platforms of support before bringing some members to build a social network around this important initiative. The problem is the process of doing community building involves doing as little as possible to attract like-minded people.

For now what we see is that the success of the Baha'i Association for Women and Girls is being promoted by the two organizations. Some women who have signed up for the board for the meetings even started to organize in advance so everyone was getting involved in organising the discussions for the meeting! All the men working with the women said they feel comfortable with that.

The same thing also happened with the idea of an Islamic Women's Initiative at conferences that women will discuss to improve the experience for women here. In their words of their event, "It's important for us as human beings to see our own differences not as a barrier to action
----------------------------------------------------------------------
5/5 completed
Generated: The future of transportation might provide one simple answer: A more autonomous society.

This idea might sound outlandish after all. A century ago, technology and capitalism made much more efficient automobiles (with more fuel). But today, as automakers shift away from electrification and into autonomous transportation, the number of cars has dwindled dramatically, and is poised to end up as one of the largest transportation infrastructure programs, a $600 billion infrastructure expenditure in the U.S., and 1,300 roads every day.

We need a change

Yet the current system isn't even close to making this transformative innovation sustainable.

At a recent conference in Las Vegas, Musk pointed to a potential road network that could grow 20 times faster, improve highway safety, and replace every five seconds. If the future of commerce depends on this vision, then the U.S. could soon be the first country in the world to be at the crossroads between these technologies.

To give you an example, imagine a highway that has four lanes. On each lane, a red light gives you a right to accelerate. On other lanes, drivers get the option of going to the wrong turn.

With all that space, congestion at every traffic crosswalk, and congestion in other places of traffic, one
----------------------------------------------------------------------

Run 2 generation completed!

In [27]:
results_df_run2 = pd.DataFrame(generated_results_run2)

generation_csv_run2 = "generated_outputs_run2.csv"

results_df_run2.to_csv(
    generation_csv_run2,
    index=False
)

print("Run 2 output file created:", generation_csv_run2)

display(results_df_run2)

Run 2 output file created: generated_outputs_run2.csv

,prompt,temperature,max_length,generated_text
0,Exploring a new country can teach us,1.0,70,"Exploring a new country can teach us lessons, ..."
1,Creativity becomes stronger when,1.1,80,Creativity becomes stronger when there is a hi...
2,A surprising discovery in science could,1.0,75,A surprising discovery in science could have a...
3,Working with people from different cultures can,1.2,85,Working with people from different cultures ca...
4,The future of transportation might,1.1,75,The future of transportation might provide one...

In [28]:
observations_run2 = """
Task 3 - Text Generation Run 2 Observations

For the second run, GPT-2 was tested with higher temperature
settings between 1.0 and 1.2 across five different prompts.

The increased temperature allowed the model to produce more
diverse and less predictable responses. Some outputs showed
greater variation in wording and ideas compared with the first run.

The different max_length values also affected how much text the
model was able to generate for each prompt.

Overall, this run demonstrated that increasing the temperature
can encourage more varied text generation, although very high
values may sometimes reduce the consistency of the output.
"""

observations_path_run2 = "generation_observations_run2.txt"

with open(
    observations_path_run2,
    "w",
    encoding="utf-8"
) as file:
    file.write(observations_run2)

print("Observations file created:", observations_path_run2)

Observations file created: generation_observations_run2.txt

In [29]:
mlflow.set_experiment("HuggingFace_Text_Generation")

with mlflow.start_run(run_name="Text_Generation_Run_2"):

    # Parameters
    mlflow.log_param(
        "model_name",
        generation_model_name
    )

    for i, settings in enumerate(settings_run2, start=1):

        mlflow.log_param(
            f"prompt_{i}_temperature",
            settings["temperature"]
        )

        mlflow.log_param(
            f"prompt_{i}_max_length",
            settings["max_length"]
        )

    # Metric
    mlflow.log_metric(
        "number_of_prompts",
        len(prompts_run2)
    )

    # Artifacts
    mlflow.log_artifact(generation_csv_run2)
    mlflow.log_artifact(observations_path_run2)

    print("MLflow Text Generation Run 2 completed!")

2026/08/15 21:15:04 INFO mlflow.tracking.fluent: Experiment with name 'HuggingFace_Text_Generation' does not exist. Creating a new experiment.

MLflow Text Generation Run 2 completed!

Observation: GPT-2 successfully generated text for all five prompts using different temperature and maximum-length settings. The lower-temperature run produced more consistent outputs, while the higher-temperature run generated more varied responses. The results demonstrate that temperature influences the creativity and randomness of generated text, whereas max_length controls the possible length of the output.